// frontend/src/app/(contents)/contact/page.tsx
'use client'

import { useActionState } from 'react'
import React from 'react'

import { Chip, ChipSize } from '@/components/bases/Chip'
import { ColorType, FontSizeType } from '@/types'

import { submitContact } from './actions'
import styles from './styles.module.scss'

interface FormState {
    errors?: Record<string, string>
    message?: string
    success?: boolean
}

const initialState: FormState = {
    message: '',
    errors: {},
}

const ContactPage: React.FC = () => {
    const [state, formAction, pending] = useActionState(submitContact, initialState)

    return (
        <div className={styles['page-contact']}>
            {!state?.success && (
                <div className={styles['contact-introduction']}>
                    <p>
                        お問い合わせ・
                        <br className={styles['sm']} />
                        ご意見・ご相談はこちらから
                    </p>
                </div>
            )}

            <div className={styles['content-wrapper']}>
                <div className={styles['content-form-wrapper']}>
                    {!state?.success ? (
                        <div className={styles['form-container']}>
                            {state?.message && (
                                <div aria-live="polite" className={styles['error-message']}>
                                    {state.message}
                                </div>
                            )}

                            <form action={formAction}>
                                {/* お名前 */}
                                <div className={styles['require-form']}>
                                    <label htmlFor="name">お名前</label>
                                    <div className={styles['chip-container']}>
                                        <Chip color={ColorType.Danger} fontColor="#b84150" fontSize={FontSizeType.SmMd} size={ChipSize.Small}>
                                            必須
                                        </Chip>
                                    </div>
                                    <input
                                        className={state?.errors?.name ? styles['error'] : ''}
                                        id="name"
                                        maxLength={20}
                                        name="name"
                                        required
                                        type="text"
                                    />
                                    {state?.errors?.name && <span className={styles['field-error']}>{state.errors.name}</span>}
                                </div>

                                {/* 会社名 */}
                                <div className={styles['form-field']}>
                                    <label htmlFor="company">会社名</label>
                                    <input id="company" maxLength={20} name="company" type="text" />
                                    {state?.errors?.company && <span className={styles['field-error']}>{state.errors.company}</span>}
                                </div>

                                {/* 電話番号 */}
                                <div className={styles['form-field']}>
                                    <label htmlFor="phoneNumber">電話番号(-を入れずに入力)</label>
                                    <input id="phoneNumber" name="phoneNumber" type="tel" />
                                    {state?.errors?.phoneNumber && <span className={styles['field-error']}>{state.errors.phoneNumber}</span>}
                                </div>

                                {/* メールアドレス */}
                                <div className={styles['require-form']}>
                                    <label htmlFor="email">メールアドレス</label>
                                    <div className={styles['chip-container']}>
                                        <Chip color={ColorType.Danger} fontColor="#b84150" fontSize={FontSizeType.SmMd} size={ChipSize.Small}>
                                            必須
                                        </Chip>
                                    </div>
                                    <input
                                        className={state?.errors?.email ? styles['error'] : ''}
                                        id="email"
                                        maxLength={50}
                                        name="email"
                                        required
                                        type="email"
                                    />
                                    {state?.errors?.email && <span className={styles['field-error']}>{state.errors.email}</span>}
                                </div>

                                {/* お問い合わせ内容 */}
                                <div className={styles['require-form']}>
                                    <label htmlFor="content">お問い合わせ内容</label>
                                    <div className={styles['chip-container']}>
                                        <Chip color={ColorType.Danger} fontColor="#b84150" fontSize={FontSizeType.SmMd} size={ChipSize.Small}>
                                            必須
                                        </Chip>
                                    </div>
                                    <textarea
                                        className={state?.errors?.content ? styles['error'] : ''}
                                        id="content"
                                        name="content"
                                        required
                                        rows={5}
                                    />
                                    {state?.errors?.content && <span className={styles['field-error']}>{state.errors.content}</span>}
                                </div>

                                <div className={styles['submit-container']}>
                                    <button className={styles['submit-button']} disabled={pending} type="submit">
                                        {pending ? '送信中...' : '送信する'}
                                    </button>
                                </div>
                            </form>
                        </div>
                    ) : (
                        <div className={styles['content-message-wrapper']}>
                            <strong>お問い合わせを送信しました</strong>
                        </div>
                    )}
                </div>
            </div>
        </div>
    )
}

export default ContactPage

// client/app/pages/contact/index.vue
<template>
    <v-container class="page-contact">
        <v-container class="page-title-container">
            <h2 class="page-title text-sm-h3 text-h4">CONTACT</h2>
        </v-container>
        <div v-if="!isSent" class="contact-introduction">
            <p>お問い合わせ・<br class="sm" />ご意見・ご相談はこちらから</p>
        </div>
        <v-sheet>
            <v-container>
                <v-sheet class="content-form-wrapper">
                    <template v-if="!isSent">
                        <v-container>
                            <c-error :errors.sync="errors" />
                            <v-form ref="form" v-model="valid" lazy-validation>
                                <div class="require-form">
                                    <v-chip v-if="!contact.name" class="require-chip">必須</v-chip>
                                    <v-text-field v-model="contact.name" :rules="nameRules" label="お名前" outlined counter="20" />
                                </div>
                                <v-text-field v-model="contact.company" :rules="companyRules" label="会社名" outlined counter="20" />
                                <v-text-field
                                    v-model="contact.phoneNumber"
                                    :rules="phoneRules"
                                    label="電話番号(-を入れずに入力)"
                                    validate-on-blur
                                    outlined
                                />
                                <div class="require-form">
                                    <v-chip v-if="!contact.email" class="require-chip">必須</v-chip>
                                    <v-text-field v-model="contact.email" :rules="emailRules" label="メールアドレス" outlined validate-on-blur />
                                </div>
                                <div class="require-form">
                                    <v-chip v-if="!contact.content" class="require-chip">必須</v-chip>
                                    <v-textarea v-model="contact.content" :rules="contentRules" label="お問い合わせ内容" outlined />
                                </div>
                                <div class="text-center">
                                    <v-btn color="primary" :disabled="!valid" @click="confirmHandler">送信する</v-btn>
                                </div>
                            </v-form>
                        </v-container>
                    </template>
                    <v-container v-else class="content-message-wrapper">
                        <strong>お問い合せを送信しました</strong>
                    </v-container>
                </v-sheet>
            </v-container>
        </v-sheet>
    </v-container>
</template>

<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'
import { min20, min50, newContact, required, validEmail, validPhoneNumber } from '~/methods'
import { IContact, IError } from '~/types'
@Component({
    head: {
        meta: [
            {
                hid: 'robots',
                name: 'robots',
                content: 'noindex',
            },
        ],
    },
})
export default class PageContactIndex extends Vue {
    contact: IContact = newContact()

    isSent: boolean = false

    valid: boolean = false

    errors: Array<IError> = []

    nameRules = [required, min20]

    companyRules = [min20]

    phoneRules = [validPhoneNumber]

    emailRules = [required, min50, validEmail]

    contentRules = [required]

    async confirmHandler() {
        this.errors = []
        const refs: any = this.$refs.form
        await refs.validate()
        try {
            if (!this.valid) {
                return
            }
            await this.$axios.$post(`/contact`, this.contact)
            this.isSent = true
            await setTimeout(() => {
                return this.$router.push('/')
            }, 3000)
        } catch (e) {
            this.errors.push(e)
        }
    }
}
</script>

<style lang="stylus" scoped>
.page-title-container
    text-align center
    +sm()
        display none
    .page-title
        margin-bottom 20px
        color $site-title-text-color
        text-align center

.contact-introduction
    text-align center
    .sm
        display none
        +sm()
            display block

.content-form-wrapper
    .require-form
        position relative
        .require-chip
            position absolute
            top 13px
            right 20px
            background-color $danger-bg-color
            color $danger-color
    .content-message-wrapper
        text-align center
</style>
