// frontend/src/components/layouts/AdminHeader/index.tsx
'use client'

import { AccountCircle, Close, Description, Email, Menu, ShoppingCart, Tag, Web } from '@mui/icons-material'
import { useRouter } from 'next/navigation'
import { useState } from 'react'


import styles from './styles.module.scss'

interface AdminHeaderProps {
    isLoggedIn?: boolean
    onLogout?: () => void
}

interface NavigationItem {
    icon: React.ComponentType
    link: string
    name: string
}

const AdminHeader: React.FC<AdminHeaderProps> = ({ isLoggedIn = true, onLogout }) => {
    const router = useRouter()
    const [sidebarVisible, setSidebarVisible] = useState<boolean>(false)
    const [dialogVisible, setDialogVisible] = useState<boolean>(false)

    const navigationItems: NavigationItem[] = [
        { icon: AccountCircle, link: '/admin/seo', name: 'SEO' },
        { icon: ShoppingCart, link: '/admin/product', name: '商品' },
        { icon: Tag, link: '/admin/classification', name: '分類' },
        { icon: Web, link: '/admin/site', name: 'サイト' },
        { icon: Email, link: '/admin/contact', name: 'お問い合わせ' },
        { icon: Description, link: '/admin/csv', name: 'CSV' },
    ]

    const handleLogout = () => {
        setDialogVisible(false)
        onLogout?.()
        router.push('/admin/user/login')
    }

    const handleNavigationClick = (link: string) => {
        router.push(link)
        setSidebarVisible(false)
    }

    return (
        <div className={styles['admin-header']}>
            <header className={styles['app-bar']}>
                <div className={styles['toolbar']}>
                    {isLoggedIn && (
                        <button
                            aria-label="open drawer"
                            className={styles['menu-button']}
                            onClick={() => setSidebarVisible(!sidebarVisible)}
                            type="button"
                        >
                            <Menu />
                        </button>
                    )}
                    <h1 className={styles['title']}>tku</h1>
                    <div className={styles['spacer']} />
                    {isLoggedIn && (
                        <button
                            className={styles['logout-button']}
                            onClick={() => setDialogVisible(true)}
                            type="button"
                        >
                            ログアウト
                        </button>
                    )}
                </div>
            </header>

            {isLoggedIn && (
                <div className={`${styles['drawer']} ${sidebarVisible ? styles['drawer-open'] : ''}`}>
                    <div className={styles['drawer-backdrop']} onClick={() => setSidebarVisible(false)} />
                    <nav className={styles['drawer-content']}>
                        <div className={styles['drawer-header']}>
                            <h2 className={styles['drawer-title']}>設定</h2>
                            <button
                                className={styles['close-button']}
                                onClick={() => setSidebarVisible(false)}
                                type="button"
                            >
                                <Close />
                            </button>
                        </div>
                        <div className={styles['divider']} />
                        <ul className={styles['navigation-list']}>
                            {navigationItems.map((item) => {
                                const IconComponent = item.icon
                                return (
                                    <li key={item.name}>
                                        <button
                                            className={styles['nav-item']}
                                            onClick={() => handleNavigationClick(item.link)}
                                            type="button"
                                        >
                                            <span className={styles['nav-icon']}>
                                                <IconComponent />
                                            </span>
                                            <span className={styles['nav-text']}>{item.name}</span>
                                        </button>
                                    </li>
                                )
                            })}
                        </ul>
                    </nav>
                </div>
            )}

            {dialogVisible && (
                <div className={styles['dialog-overlay']}>
                    <div className={styles['dialog-backdrop']} onClick={() => setDialogVisible(false)} />
                    <div className={styles['dialog']}>
                        <div className={styles['dialog-header']}>
                            <h3 className={styles['dialog-title']}>ログアウト</h3>
                        </div>
                        <div className={styles['dialog-content']}>
                            <p>ログアウトします。よろしいですか？</p>
                        </div>
                        <div className={styles['dialog-actions']}>
                            <button
                                className={styles['dialog-button-secondary']}
                                onClick={() => setDialogVisible(false)}
                                type="button"
                            >
                                いいえ
                            </button>
                            <button
                                className={styles['dialog-button-primary']}
                                onClick={handleLogout}
                                type="button"
                            >
                                はい
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}

export default AdminHeader

// client/app/components/AdminHeader.vue
<template>
    <div class="admin-header">
        <v-app-bar app :color="ColorType.Primary" dark clipped-left>
            <v-app-bar-nav-icon v-if="!$store.getters['user/isGuest']" @click="sidebarVisible = !sidebarVisible">
                <client-only>
                    <c-icon :type="IconType.Menu.name" @click.native="sidebarVisible = !sidebarVisible" />
                </client-only>
            </v-app-bar-nav-icon>
            <v-app-bar-title>tku</v-app-bar-title>
            <v-spacer />
            <v-dialog v-if="!$store.getters['user/isGuest']" v-model="dialogVisible" width="400">
                <template #activator="{ on, attrs }">
                    <v-btn outlined v-bind="attrs" v-on="on">ログアウト</v-btn>
                </template>
                <v-card class="sigh-out-area">
                    <v-card-title />
                    <v-card-text class="sigh-out-text">ログアウトします。よろしいですか？</v-card-text>
                    <v-divider class="divider" />
                    <v-card-actions class="sigh-out-actions">
                        <v-btn color="primary" outlined @click="dialogVisible = false">いいえ</v-btn>
                        <v-btn color="primary" @click="logoutHandler">はい</v-btn>
                    </v-card-actions>
                </v-card>
            </v-dialog>
        </v-app-bar>
        <v-navigation-drawer v-if="!$store.getters['user/isGuest']" v-model="sidebarVisible" class="admin-navigation" clipped app>
            <v-container>
                <v-list-item class="navigation-list">
                    <v-list-item-content class="navigation-list-item">
                        <v-list-item-title class="title navigation-title"> 設定 </v-list-item-title>
                    </v-list-item-content>
                </v-list-item>
                <v-divider class="divider" />
                <v-list dense nav>
                    <v-list-item v-for="(table, index) in tables" :key="index" nuxt :to="`/admin/${table.link}`">
                        <v-list-item-icon>
                            <v-icon>{{ table.icon }}</v-icon>
                        </v-list-item-icon>
                        <v-list-item-content>
                            <v-list-item-title> {{ table.name }} </v-list-item-title>
                        </v-list-item-content>
                    </v-list-item>
                </v-list>
            </v-container>
        </v-navigation-drawer>
    </div>
</template>

<script lang="ts">
import { mdiAccount, mdiApplicationOutline, mdiCartVariant, mdiEmail, mdiFileDocument, mdiTagOutline } from '@mdi/js'
import { Component, Vue } from 'nuxt-property-decorator'
import { ColorType, IconType, ITable } from '~/types'
@Component({})
export default class AdminHeader extends Vue {
    ColorType: typeof ColorType = ColorType
    IconType: typeof IconType = IconType

    tables: Array<ITable> = [
        { name: 'SEO', link: 'seo', icon: mdiAccount },
        { name: '商品', link: 'product', icon: mdiCartVariant },
        { name: '分類', link: 'classification', icon: mdiTagOutline },
        { name: 'サイト', link: 'site', icon: mdiApplicationOutline },
        { name: 'お問い合わせ', link: 'contact', icon: mdiEmail },
        { name: 'CSV', link: 'csv', icon: mdiFileDocument },
    ]

    sidebarVisible: boolean = false
    dialogVisible: boolean = false

    async logoutHandler() {
        await this.$store.dispatch('user/logoutUser')
        this.$router.replace('/admin/user/login')
    }
}
</script>

<style lang="stylus" scoped>
.sigh-out-area
    .sigh-out-text
        text-align center
        font-size $font-medium
    .sigh-out-actions
        display flex
        justify-content center

.admin-navigation
    .navigation-list
        .navigation-list-item
            .navigation-title
                color $title-primary-color
</style>
